### ISSUE TITLE
Getting 500 status codes for anything that isn't 2xx status code

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [feathersjs-ecosystem/feathers-objection#112]
I'm running this code

```javascript
const { Service } = require('feathers-objection')
const { NotFound, BadRequest } = require('@feathersjs/errors')

exports.Sessions = class Sessions extends Service {
  constructor(options) {
    const { Model, ...otherOptions } = options

    super({
      ...otherOptions,
      model: Model,
    })
  }

  async create(data) {
    const session = await this.Model.query().insertGraph(data)

    return session
  }

  async patch(id, data, params) {
    if (data.status) {
      const session = await this.Model.query().findById(id)

      if (!session) {
        throw new NotFound(
          'Cant update session status because session was not found'
        )
      }

      if (
        session.status === 'waiting' &&
        (data.status === 'ended' || data.status === 'completed')
      ) {
        throw new BadRequest(
          'Cant update session status because an invalid session status was specifed. Current session status is "waiting" and the only valid status change is "in progress".'
        )
      }

      if (session.status === 'in progress' && data.status === 'completed') {
        throw new BadRequest(
          'Cant update session status because an invalid session status was specifed. Current session status is "in progress" and cant be changed to "completed".'
        )
      }
      console.log('=====> We can fire off status change logic here.')
    }

    return super.patch(id, data, params)
  }
}
```

And the response is a `500` with the body below

```json
{
  "error": {
    "message": "Cant update session status because an invalid session status was specifed. Current session status is \"in progress\" and cant be changed to \"completed\".",
    "stack": "BadRequest: Cant update session status because an invalid session status was specifed. Current session status is \"in progress\" and cant be changed to \"completed\".\n    at new BadRequest (/app/node_modules/@feathersjs/errors/lib/index.js:86:17)\n    at Object.patch (/app/src/services/sessions/sessions.class.js:40:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "type": "FeathersError",
    "name": "BadRequest",
    "code": 400,
    "className": "bad-request",
    "errors": {},
    "hook": {
      "type": "before",
      "method": "patch",
      "path": "sessions",
      "params": {
        "permitted": true,
        "query": {},
        "route": {},
        "provider": "rest",
        "headers": {
          "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL3BvbmQuZGV2L3VzZXIiOnsicGVybWlzc2lvbnMiOlsiRmFjaWxpdGF0b3IiXSwicm9sZSI6IkZhY2lsaXRhdG9yIn0sImlzcyI6Imh0dHBzOi8vdXJnZW50Y2FyZWtpZHMtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjIzMDIyMTg5NmFkNTAwMzhjOGU4YzUiLCJhdWQiOiJodHRwczovL3BvbmQuZGV2IiwiaWF0IjoxNTk5MDAxOTczLCJleHAiOjE1OTkwODgzNzMsImF6cCI6IklVaGdIWnFqeEl2NkMxRG9taVZLWFVuMW8wNzZzNFpiIiwiZ3R5IjoicGFzc3dvcmQifQ.JlPz9DJTGMFxnGMXPED616JTBtN1L5tOOnj9_31C1R0",
          "accept": "application/json",
          "content-type": "application/json",
          "user-agent": "PostmanRuntime/7.26.1",
          "cache-control": "no-cache",
          "postman-token": "64eb1ee8-ed86-460e-b3f6-048e96847f59",
          "host": "localhost:3040",
          "accept-encoding": "gzip, deflate, br",
          "connection": "keep-alive",
          "content-length": "25"
        },
        "authentication": {
          "strategy": "jwt",
          "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL3BvbmQuZGV2L3VzZXIiOnsicGVybWlzc2lvbnMiOlsiRmFjaWxpdGF0b3IiXSwicm9sZSI6IkZhY2lsaXRhdG9yIn0sImlzcyI6Imh0dHBzOi8vdXJnZW50Y2FyZWtpZHMtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjIzMDIyMTg5NmFkNTAwMzhjOGU4YzUiLCJhdWQiOiJodHRwczovL3BvbmQuZGV2IiwiaWF0IjoxNTk5MDAxOTczLCJleHAiOjE1OTkwODgzNzMsImF6cCI6IklVaGdIWnFqeEl2NkMxRG9taVZLWFVuMW8wNzZzNFpiIiwiZ3R5IjoicGFzc3dvcmQifQ.JlPz9DJTGMFxnGMXPED616JTBtN1L5tOOnj9_31C1R0",
          "payload": {
            "https://pond.dev/user": {
              "permissions": [
                "Facilitator"
              ],
              "role": "Facilitator"
            },
            "iss": "https://urgentcarekids-dev.us.auth0.com/",
            "sub": "auth0|5f230221896ad50038c8e8c5",
            "aud": "https://pond.dev",
            "iat": 1599001973,
            "exp": 1599088373,
            "azp": "IUhgHZqjxIv6C1DomiVKXUn1o076s4Zb",
            "gty": "password"
          }
        },
        "authenticated": true,
        "user": {
          "permissions": [
            "Facilitator"
          ],
          "role": "Facilitator",
          "auth0Id": "auth0|5f230221896ad50038c8e8c5",
          "id": 12321,
          "organizationId": 1,
          "locationId": 1
        }
      },
      "id": 467,
      "data": {
        "status": "completed"
      }
    }
  }
}
```

How do I get the correct status codes returned?

**Comment by dekelev** [comment]
Hi @RyanAtViceSoftware , As far as I can see here, you're extending the feathers-objection Service class and when you get a request to your patch method, you throw an error and the super.patch method would not be called, so the lib cannot affect your return status code, which should be 400 (BadRequest).

Can you please debug this and see if it's related to the feathers-objection lib at all?
