### ISSUE TITLE
using $noSelect throws an error

### ISSUE THREAD

**Issue by ewingrj** [feathersjs-ecosystem/feathers-objection#57]
From what I can tell, the $noSelect needs to be a query param. However when including it as a queryParam, feathers throws the following error:

```
error: BadRequest: Invalid query parameter $noSelect
    at new BadRequest (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/node_modules/@feathersjs/errors/lib/index.js:86:17)
    at commons_1._.each (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:41:27)
    at Object.keys.forEach.key (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/node_modules/@feathersjs/commons/lib/utils.js:15:45)
    at Array.forEach (<anonymous>)
    at Object.each (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/node_modules/@feathersjs/commons/lib/utils.js:15:30)
    at cleanQuery (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:35:21)
    at Object.filterQuery [as default] (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/filter-query.js:87:20)
    at Object.filterQuery (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/service.js:45:46)
    at Object._patch (/Users/rjewing/code/personal/evolution/packages/api/node_modules/feathers-objection/lib/index.js:513:14)
    at callMethod (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/service.js:12:22)
    at Object.patch (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/adapter-commons/lib/service.js:83:16)
    at processHooks.call.then.hookObject (/Users/rjewing/code/personal/evolution/packages/api/node_modules/@feathersjs/feathers/lib/hooks/index.js:56:27)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by dekelev** [comment]
Any non-standard query operator needs to be explicitly whitelisted in the service file:

https://blog.feathersjs.com/feathers-2019-new-years-news-f478d5f2c8cd#60e1
